<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <RootNamespace>Ustin.Work.LessMess.UmbarcoWrapper.Api</RootNamespace>
    <AssemblyName>Ustin.Work.LessMess.UmbarcoWrapper.Api</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Ustin.Work.LessMess.UmbarcoWrapper.Infrastructure\Ustin.Work.LessMess.UmbarcoWrapper.Infrastructure.csproj" />
  </ItemGroup>

</Project>
